### PR TITLE
Create Calling - JavaScript Web.md

### PR DESCRIPTION
**Pull request by LaithRodan**
Solidifying JS release notes

### CODE REVIEW

**Comment by LaithRodan** [comment]
#signoff

**Comment by jorgegarchirota** [comment]
@LaithRodan , we already have a Calling JS release note file, is this a new one or which is the difference?
https://github.com/Azure/Communication/blob/master/releasenotes/acs-javascript-calling-library-release-notes.md

**Comment by ProbablePrime** [comment]
@LaithRodan please see Jorge's query.

**Comment by LaithRodan** [comment]
> @LaithRodan , we already have a Calling JS release note file, is this a new one or which is the difference?
> https://github.com/Azure/Communication/blob/master/releasenotes/acs-javascript-calling-library-release-notes.md

I'm closing this pull request this was picked up and handled by Katya.

**Pull request closed without merging**
